dataRootPath = "C:/Users/Stefano/Desktop/data-root/"
ephysRecordingPath = "C:/Users/Stefano/Desktop/recordings/ephys/"
cam1Path = "C:/Users/Stefano/Desktop/recordings/cam-1-frontal/"
cam2Path = "C:/Users/Stefano/Desktop/recordings/cam-2-lateral/"
