dataRootPath = "C:/Users/Stefano/Desktop/data-root/"
ephysRecordingPath = "/home/ginko/test/ephys/"
cam1Path = "C:/Users/Stefano/Desktop/cam-1-frontal/"
cam2Path = "C:/Users/Stefano/Desktop/cam-2-lateral/"
